parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''

api_platform:
    eager_loading:
        max_joins: 30
    collection:
        pagination:
            enabled: false
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
    enable_fos_user: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Larping API
    version: 0.0.1
